In [12]:
import pandas as pd
import numpy as np

In [13]:
df = pd.read_csv(
    "C:/Projects/Retail Sales Prediction & Business Performance Analytics/data/featured_data.csv",
    parse_dates=["Date"]
)

df.head()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,StoreType,...,PromoMonths,SalesPerCustomer,CompetitionNearby,StoreAgeDays,Lag_1,Lag_7,Lag_30,Rolling7Mean,Rolling30Mean,Rolling7Std
0,1,2,2013-01-01,0,0,0,0,a,1,c,...,0.0,0.000000,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,3,2013-01-02,5530,668,1,0,0,1,c,...,0.0,8.278443,0,1,0.0,0.0,0.0,0.0,0.0,0.0
2,1,4,2013-01-03,4327,578,1,0,0,1,c,...,0.0,7.486159,0,2,5530.0,0.0,0.0,0.0,0.0,0.0
3,1,5,2013-01-04,4486,619,1,0,0,1,c,...,0.0,7.247173,0,3,4327.0,0.0,0.0,0.0,0.0,0.0
4,1,6,2013-01-05,4997,635,1,0,0,1,c,...,0.0,7.869291,0,4,4486.0,0.0,0.0,0.0,0.0,0.0

In [14]:
print(df.shape)

display(df.head())

df.info()

(1017209, 41)

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,StoreType,...,PromoMonths,SalesPerCustomer,CompetitionNearby,StoreAgeDays,Lag_1,Lag_7,Lag_30,Rolling7Mean,Rolling30Mean,Rolling7Std
0,1,2,2013-01-01,0,0,0,0,a,1,c,...,0.0,0.000000,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,3,2013-01-02,5530,668,1,0,0,1,c,...,0.0,8.278443,0,1,0.0,0.0,0.0,0.0,0.0,0.0
2,1,4,2013-01-03,4327,578,1,0,0,1,c,...,0.0,7.486159,0,2,5530.0,0.0,0.0,0.0,0.0,0.0
3,1,5,2013-01-04,4486,619,1,0,0,1,c,...,0.0,7.247173,0,3,4327.0,0.0,0.0,0.0,0.0,0.0
4,1,6,2013-01-05,4997,635,1,0,0,1,c,...,0.0,7.869291,0,4,4486.0,0.0,0.0,0.0,0.0,0.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1017209 entries, 0 to 1017208
Data columns (total 41 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   Store                      1017209 non-null  int64
 1   DayOfWeek                  1017209 non-null  int64
 2   Date                       1017209 non-null  datetime64[ns]
 3   Sales                      1017209 non-null  int64
 4   Customers                  1017209 non-null  int64
 5   Open                       1017209 non-null  int64
 6   Promo                      1017209 non-null  int64
 7   StateHoliday               1017209 non-null  object
 8   SchoolHoliday              1017209 non-null  int64
 9   StoreType                  1017209 non-null  object
 10  Assortment                 1017209 non-null  object
 11  CompetitionDistance        1017209 non-null  float64
 12  CompetitionOpenSinceMonth  1017209 non-null  float64
 13  CompetitionOpenSinceYear   1017209 non-null  float64
 14  Promo2                     1017209 non-null  int64
 15  Promo2SinceWeek            1017209 non-null  float64
 16  Promo2SinceYear            1017209 non-null  float64
 17  PromoInterval              1017209 non-null  object
 18  Year                       1017209 non-null  int64
 19  Month                      1017209 non-null  int64
 20  Quarter                    1017209 non-null  int64
 21  WeekOfYear                 1017209 non-null  int64
 22  Day                        1017209 non-null  int64
 23  DayOfYear                  1017209 non-null  int64
 24  Weekday                    1017209 non-null  object
 25  MonthName                  1017209 non-null  object
 26  IsHoliday                  1017209 non-null  int64
 27  IsWeekend                  1017209 non-null  int64
 28  IsMonthStart               1017209 non-null  int64
 29  IsMonthEnd                 1017209 non-null  int64
 30  CompetitionMonthsOpen      1017209 non-null  float64
 31  PromoMonths                1017209 non-null  float64
 32  SalesPerCustomer           1017209 non-null  float64
 33  CompetitionNearby          1017209 non-null  int64
 34  StoreAgeDays               1017209 non-null  int64
 35  Lag_1                      1017209 non-null  float64
 36  Lag_7                      1017209 non-null  float64
 37  Lag_30                     1017209 non-null  float64
 38  Rolling7Mean               1017209 non-null  float64
 39  Rolling30Mean              1017209 non-null  float64
 40  Rolling7Std                1017209 non-null  float64
dtypes: datetime64[ns](1), float64(14), int64(20), object(6)
memory usage: 318.2+ MB

In [15]:
columns_to_remove = [
    "Lag_1",
    "Lag_7",
    "Lag_30",
    "Rolling7Mean",
    "Rolling30Mean",
    "Rolling7Std"
]

df.drop(
    columns=columns_to_remove,
    inplace=True
)

In [16]:
df.rename(columns={

    "Promo":"Promotion",

    "Promo2":"Continuous Promotion",

    "CompetitionDistance":"Competition Distance",

    "CompetitionMonthsOpen":"Competition Months Open",

    "PromoMonths":"Promotion Duration (Months)",

    "CompetitionNearby":"Competition Nearby",

    "StoreType":"Store Type",

    "StateHoliday":"State Holiday"

}, inplace=True)

In [17]:
df["Promotion"] = df["Promotion"].replace({

    0:"No",

    1:"Yes"

})

df["Continuous Promotion"] = df["Continuous Promotion"].replace({

    0:"No",

    1:"Yes"

})

df["Competition Nearby"] = df["Competition Nearby"].replace({

    0:"No",

    1:"Yes"

})

df["IsHoliday"] = df["IsHoliday"].replace({

    0:"No",

    1:"Yes"

})

df["IsWeekend"] = df["IsWeekend"].replace({

    0:"Weekday",

    1:"Weekend"

})

In [18]:
df.drop(columns=["SalesPerCustomer"], inplace=True)

In [19]:
df.drop(columns=["Weekday"], inplace=True)

In [20]:
df.drop(columns=["MonthName"], inplace=True)

In [21]:
print(df.shape)

display(df.head())

df.info()

(1017209, 32)

,Store,DayOfWeek,Date,Sales,Customers,Open,Promotion,State Holiday,SchoolHoliday,Store Type,...,Day,DayOfYear,IsHoliday,IsWeekend,IsMonthStart,IsMonthEnd,Competition Months Open,Promotion Duration (Months),Competition Nearby,StoreAgeDays
0,1,2,2013-01-01,0,0,0,No,a,1,c,...,1,1,Yes,Weekday,1,0,52.0,0.0,No,0
1,1,3,2013-01-02,5530,668,1,No,0,1,c,...,2,2,No,Weekday,0,0,52.0,0.0,No,1
2,1,4,2013-01-03,4327,578,1,No,0,1,c,...,3,3,No,Weekday,0,0,52.0,0.0,No,2
3,1,5,2013-01-04,4486,619,1,No,0,1,c,...,4,4,No,Weekday,0,0,52.0,0.0,No,3
4,1,6,2013-01-05,4997,635,1,No,0,1,c,...,5,5,No,Weekend,0,0,52.0,0.0,No,4

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1017209 entries, 0 to 1017208
Data columns (total 32 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   Store                        1017209 non-null  int64
 1   DayOfWeek                    1017209 non-null  int64
 2   Date                         1017209 non-null  datetime64[ns]
 3   Sales                        1017209 non-null  int64
 4   Customers                    1017209 non-null  int64
 5   Open                         1017209 non-null  int64
 6   Promotion                    1017209 non-null  object
 7   State Holiday                1017209 non-null  object
 8   SchoolHoliday                1017209 non-null  int64
 9   Store Type                   1017209 non-null  object
 10  Assortment                   1017209 non-null  object
 11  Competition Distance         1017209 non-null  float64
 12  CompetitionOpenSinceMonth    1017209 non-null  float64
 13  CompetitionOpenSinceYear     1017209 non-null  float64
 14  Continuous Promotion         1017209 non-null  object
 15  Promo2SinceWeek              1017209 non-null  float64
 16  Promo2SinceYear              1017209 non-null  float64
 17  PromoInterval                1017209 non-null  object
 18  Year                         1017209 non-null  int64
 19  Month                        1017209 non-null  int64
 20  Quarter                      1017209 non-null  int64
 21  WeekOfYear                   1017209 non-null  int64
 22  Day                          1017209 non-null  int64
 23  DayOfYear                    1017209 non-null  int64
 24  IsHoliday                    1017209 non-null  object
 25  IsWeekend                    1017209 non-null  object
 26  IsMonthStart                 1017209 non-null  int64
 27  IsMonthEnd                   1017209 non-null  int64
 28  Competition Months Open      1017209 non-null  float64
 29  Promotion Duration (Months)  1017209 non-null  float64
 30  Competition Nearby           1017209 non-null  object
 31  StoreAgeDays                 1017209 non-null  int64
dtypes: datetime64[ns](1), float64(7), int64(15), object(9)
memory usage: 248.3+ MB

In [22]:
df.to_csv(

    "C:/Projects/Retail Sales Prediction & Business Performance Analytics/data/powerbi_dataset.csv",

    index=False

)

print("Power BI Dataset Exported Successfully!")

Power BI Dataset Exported Successfully!